
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >-
          Thanks for submitting an issue! I'll check it at as soon as possible
          and get back to you.
        pr-message: >-
          Thanks for submitting a PR. If the PR is a valid and passes
          all the checks , we will approve it soon. Have a great day !